name: main

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: "15 7 */9 * *"
    workflow_dispatch:

permissions:
    contents: read

jobs:
    test:
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t", "3.15", "pypy-3.11"]
                runner: [ubuntu-slim]
                include:
                    - python-version: "3.14"
                      runner: macos-latest
                    - python-version: "3.14"
                      runner: windows-latest
        runs-on: ${{ matrix.runner }}
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Setup Python
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
              with:
                  cache-suffix: "${{ matrix.python-version }}-"

            - name: Cache tox environments
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                  path: .tox
                  key: ${{ runner.os }}-${{ matrix.python-version }}-tox-${{ hashFiles('pyproject.toml', 'tox.ini') }}

            - name: Install tox
              run: uv tool install --python ${{ matrix.python-version }} --with tox-gh-actions --with tox-uv-bare tox

            - name: Test
              run: tox
